# Librerías importantes para el análisis de datos en Python

------------------------------------------------------


### Data Science and Machine Learning

#### Febrero 2023

**Aurora Cobo Aguilera**

**The Valley**

------------------------------------------------------




En este notebook, introduciremos una librería que usaremos en el resto del módulo y muy útil para realizar cálculo científico y opraciones con vectores y matrices.

El comienzo habitual de cualquier scrip de python es la importación de librerías a usar.


In [2]:
import numpy as np

## 1. Uso de la librería Numpy y matrices

El módulo _numpy_ es muy útil para cálculo científico en python.

La principal estructura de datos en _numpy_ es el array con N dimensiones. 

### 1.1. Matrices con Numpy

En Numpy una matriz se representa a través de un array de 2 dimensiones.

Puedes definir un _numpy_ _array_ a partir de una lista o una lista de listas. Python intentará construirlo con las dimensiones apropiadas. Puedes consultar las dimensiones con _shape()_


In [3]:
my_array = np.array([[1, 2], [3, 4]])
print(my_array)
print(np.shape(my_array)) #checking the dimensions

[[1 2]
 [3 4]]
(2, 2)


> **Ejercicio**: Define un nuevo array de 2x3 llamado *my_array2* con  [1, 2, 3] en la primera fila y [4,5,6] en la segunda.
Consulta las dimensiones del array.


In [4]:
#<SOL>
lista = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(lista)
print(np.shape(lista))
#</SOL>

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


Hay un número de operaciones que puedes hacer con arrays numpy. Una de las más importantes es **slicing**, que consiste en extraer un subarray de un array.

In [5]:
my_array3 = my_array[:, 1] #de todas las filas coge la columna numero 1
print(my_array3)
print(my_array3[1,]) #de la fila 1 printea las columnas de la 0 a la 2 (no incluida la dos)

[2 4]
4


Algo importante a considerar cuando haces slicing son las dimensiones del array de salida. 

>**Ejercicio**: Consulta las dimensiones de *my_array3*. Consulta tambien sus dimensiones con la función _ndim_:





In [6]:
#help(np.ndarray.ndim)
#<SOL>
lista2 = lista[1:]
print(lista2)
print(np.shape(lista2))
lista2.ndim
#</SOL>


[[ 5  6  7  8]
 [ 9 10 11 12]]
(2, 4)


2

Si lo has calculado correctamente, verás que *my_array3* es de 1 dimensión. Esto puede ser un problema cuando trabajas con matrices de 2 dimensiones (y con vectores que se consideran de 2D con uno de los tamaños igual a 1). Para resolver esto, _numpy_ proporciona la constante _newaxis_.




In [45]:
my_array3 = my_array3[:, np.newaxis] #hace de un vector de numeros, una matrix nx1

>**Ejercicio**: Consulta de nuevo la dimensión de *my_array3*.


In [46]:
#<SOL>
print(np.shape(my_array3))
#<SOL>

(2, 1, 1)


Otro método importante de manipulación de array es _concatenation_ o _stacking_. Es útil para siempre declarar en qué dirección queremos apilar arrays. Por ejemplo, en la siguiente celda apilamos verticalmente. 

In [49]:
print(np.concatenate( (my_array[:,0], lista[:,1]) , axis=0)) # columnwise concatenation

[ 1  3  2  6 10]


> **Ejercicio**: *Concatena* la primera columna de *my_array* y la segunda columna de *my_array2*

In [10]:
#<SOL>
print(np.concatenate((lista, lista2), axis =0))
#help(np.concatenate)
#<SOL>

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Puedes crear _numpy_ arrays de diferentes formas, no sólo a partir de listas. Por ejemplo _numpy_ proporciona un número de funciones para crear tipos especiales de matrices.

> **Ejercicio**: Crea 3 arrays usando _ones_, _zeros_ and _eye_. Si tienes alguna duda sobre los parámetros de las funciones, mira en la ayuda con la función _help( )_.

In [41]:
#<SOL>
#help(np.ones)
#help(np.zeros)
#help(np.eye)
def HacerMatriz(dimension):
  A=np.ones(dimension)
  print('Crear matriz con no.ones')
  print(A)
  B=np.zeros(dimension)
  print('Crear Matriz con np.zeroes')
  print(B)
  C=np.eye(dimension[0], dimension[1])
  print('Crear Matriz con np.eyes')
  print(C)
  print('***********************')
  print(np.shape(A))
  print(np.ndim(A))
  D=A[:, np.newaxis]
  E=A[np.newaxis, :]
  print(D)
  print(np.shape(D))
  print(np.ndim(D))
  print(E)
  print(np.shape(E))
  print(np.ndim(E))

#<SOL>
dim=[2,2]
HacerMatriz(dim)



Crear matriz con no.ones
[[1. 1.]
 [1. 1.]]
Crear Matriz con np.zeroes
[[0. 0.]
 [0. 0.]]
Crear Matriz con np.eyes
[[1. 0.]
 [0. 1.]]
***********************
(2, 2)
2
[[[1. 1.]]

 [[1. 1.]]]
(2, 1, 2)
3
[[[1. 1.]
  [1. 1.]]]
(1, 2, 2)
3


Además _numpy_ ofrece todas las operaciones básicas con matrices: multiplicaciones, producto escalar, ...
Puedes encontrar información sobre ellas en [Numpy manual](https://numpy.org/doc/stable/user/) 



#### 1.1.1. Suma de matrices

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


#### 1.1.2. Resta de matrices

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])
print(B)
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


#### 1.1.3. Multiplicación de matrices (element-wise)

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


#### 1.1.4. División de matrices

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


#### 1.1.5. Producto escalar de matrices

In [17]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
B = np.array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


#### 1.1.6. Producto de matrices y vectores

In [18]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
B = np.array([0.5, 0.5])
print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]
[1.5 3.5 5.5]


#### 1.1.7. Producto de matrices y escalares

In [19]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
b = 0.5
print(b)
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


#### 1.1.8. Matriz transpuesta

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


#### 1.1.9. Matriz inversa

In [21]:
from numpy.linalg import inv
# define matrix
A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Además de _numpy_ hay librerías más avanzadas para cálculos científicos, _scipy_. [Scipy](https://docs.scipy.org/doc/scipy/) incluye módulos para álgebra lineal, procesado de la señal, transformadas de Fourier, ...

## Definiciones de vectores con un rango de valores

Por último fíjate en las siguientes definiciones de vectores. Son muy útiles en ML o cualquier problema en el que queramos explorar un conjunto de valores equiespaciados o según escala logarítmica.

In [57]:
arreglo1 = np.logspace(-6, 6, 13) #crea un vector logaritmico elevado desde -6 a 6, el ultimo es la cantidad de elementos
print(arreglo1)

[1.e-06 1.e-05 1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03
 1.e+04 1.e+05 1.e+06]


In [55]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


> **Ejercicio**: Define un vector con puntos desde el -100 hasta el 200 y saltos de 3 en 3.

In [58]:
#<SOL>
print(np.arange(-100, 200, 3))
#</SOL>

[-100  -97  -94  -91  -88  -85  -82  -79  -76  -73  -70  -67  -64  -61
  -58  -55  -52  -49  -46  -43  -40  -37  -34  -31  -28  -25  -22  -19
  -16  -13  -10   -7   -4   -1    2    5    8   11   14   17   20   23
   26   29   32   35   38   41   44   47   50   53   56   59   62   65
   68   71   74   77   80   83   86   89   92   95   98  101  104  107
  110  113  116  119  122  125  128  131  134  137  140  143  146  149
  152  155  158  161  164  167  170  173  176  179  182  185  188  191
  194  197]
